image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Build and Push
        runs-on:
          - self.hosted
          - linux
          - ean
        script:
          - echo ${harbor_pwd} | docker login --username "$harbor_user" --password-stdin 7u40qj0f.gra7.container-registry.ovh.net
          - IMAGE_NAME=$BITBUCKET_REPO_SLUG
          - echo $DOTENV_B64 | base64 -d > .env
          - docker build . --file Dockerfile --tag $BITBUCKET_REPO_SLUG
          - VERSION="build-${BITBUCKET_BUILD_NUMBER}"
          - IMAGE=${harbor_prj}/${IMAGE_NAME}
          - docker tag "${IMAGE_NAME}" "7u40qj0f.gra7.container-registry.ovh.net/${IMAGE}:${VERSION}"
          - docker tag "${IMAGE_NAME}" "7u40qj0f.gra7.container-registry.ovh.net/${IMAGE}:latest"
          - docker push "7u40qj0f.gra7.container-registry.ovh.net/${IMAGE}:${VERSION}"
          - docker push "7u40qj0f.gra7.container-registry.ovh.net/${IMAGE}:latest"
        services:
          - docker
        caches:
          - docker

definitions:
  services:
    docker:
      memory: 3072
